### ISSUE TITLE
Disable Editing Option if Read-only API Token

### ISSUE THREAD

**Issue by frytyler** [appbaseio/dejaVu#127]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

- Hosted web app. I only have this for contributing purpose.

#### What is the version of Dejavu that you are using?

- Latest Dev.

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

![editing dropdown](https://user-images.githubusercontent.com/1922965/31893125-ba54d1aa-b7d8-11e7-84ac-254428da648d.gif)

This shows the editing option available to a READ-ONLY api key. 

I'm suggesting that we disable this option if it's read only. This can be done on click to check access or if we already know the access disable it entirely from the beginning. 

In issue #124 there is a high chance of getting an Un-Authorized response given the attempt to edit a cell is possible. This would then prevent even being on the editing screen which would avoid the user finding out they can't edit after attempting.

**Comment by siddharthlatest** [comment]
Since the above suggestion behavior would be appbase.io specific and may not hold true for a generic ES index, what we will instead do here (to ensure this works everywhere) is to show an error message if the user doesn't have permission to make an operation.

Example: 
![screen shot 2018-01-20 at 1 44 20 am](https://user-images.githubusercontent.com/630042/35169624-33cfadb2-fd83-11e7-8b54-38c8059911c6.png)

- [x] Right now, we need to support a similar error modal behavior for the "Insert JSON" operation.

**Comment by siddharthlatest** [comment]
- [x] And a similar one when a user tries to update data (but can't, due to either permissions or some other issue).

**Comment by TCMiranda** [comment]
@siddharthlatest from this conversation and searching for similar issues I got your opinion about leaving the authorization concern for ES which already handles it. 

That is ok. But considering the feature of editing document as is, It is bad UX to let the user make an error just because the backend would deal with it while knowing that we could know if the user has the access from upfront.

Prevent the error to be done instead of providing feedback is better. Doesn't it make sense to you? 
Can you estimate how much difficult it is to make this enhancement?

This is small. But for what I'm considering dejavu as a solution, the edition UI would raise a number of security concerns for my "users" which I would prefer not to have.

**Comment by siddharthlatest** [comment]
@TCMiranda For the overall user base, this is an assumption we wouldn't want to make - as the backend security could work in very different ways. As an example, my backend could restrict certain kinds of data updates but may not restrict others. Best case I can see is for Dejavu to be neutral about this and allow the user to make the choice.

If you want to change this behavior for your use-case, you can fork the project and implement it. If you feel something could be useful back in the main project, send us a PR :-).

**Comment by TCMiranda** [comment]
Sure! It makes sense. Thanks for the feedback Siddharth

Em qua, 12 de dez de 2018 às 19:02, Siddharth Kothari <
notifications@github.com> escreveu:
