### ISSUE TITLE
User access control

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#179]
using: Docker
version: 1.5.0

# Context
Users can access all queries and ES data for any added data source.

# Feature request
It would be useful to have access control rules for various data sources and views (read, edit).

**Comment by siddharthlatest** [comment]
@brylie Our current approach is to leave out access control to the ES backend. We allow passing Basic Auth or any other custom headers for a backend to be able to decide this.

Also since Dejavu is a client-only app (and doesn't save any of the context beyond a browser's localStorage), it's not possible to enforce an access control on an ES cluster from it.

Elasticsearch's X-Pack add-ons or https://github.com/floragunncom/search-guard are two full-featured solutions that allow you to implement access control. You should check these.
