### ISSUE TITLE
saveAs is not defined

### ISSUE THREAD

**Issue by bcolucci** [appbaseio/dejaVu#187]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Local only, I'm trying to contribute.

#### What is the version of Dejavu that you are using?

I'm on the dev branch.

---

I've followed the contributor steps, ran the app, and when I've tried to click on one of the "Download as XXX" buttons, I have an error:

```
Uncaught ReferenceError: saveAs is not defined
    at o.downloadJSON (live.js:formatted:37013)
    at Object.r (live.js:formatted:6689)
    at i (live.js:formatted:6480)
    at Object.s [as executeDispatchesInOrder] (live.js:formatted:6488)
    at f (live.js:formatted:4304)
    at m (live.js:formatted:4311)
    at Array.forEach (<anonymous>)
    at r (live.js:formatted:9726)
    at Object.processEventQueue (live.js:formatted:4366)
    at r (live.js:formatted:20838)
```

```javascript
o.downloadJSON = function() {
	var e = new File([o.props.dejavuExportData],"data.json",{
		type: "application/json;charset=utf-8"
	});
	saveAs(e)
}
```

**Comment by divyanshu013** [comment]
After diving into this I realized the issue was caused due to the `file-saver` bower dependency we're using ([reference](https://github.com/eligrey/FileSaver.js/issues/409)). Seems like the bower distribution was empty in the recent package.

You can fix this by pulling the latest changes on `dev` and running `bower install` to resolve to the correct dependency. If it doesn't work, you might have to run `bower cache clean` and then run `bower install` again. Thanks for reporting, we'll roll this out in v1.6.0 🚀
