### ISSUE TITLE
ES 6 Mappings Support: "Could not convert [raw.index] to boolean" on adding datafield

### ISSUE THREAD

**Issue by sstepanovvl** [appbaseio/dejaVu#190]
Hi guys, thank you for great app!

i have a lil issue here:

**docker run -p 1358:1358 appbaseio/dejavu:1.5.0**

Elasticsearch version : "**6.2.3**"

I'm trying to create new text field and getting  **"Could not convert [raw.index] to boolean"** error on saving.

Can you show me what am i doing wrong?
Thank you for ASAP answers!

**Comment by siddharthlatest** [comment]
Thanks for reporting this @sstepanovvl! It seems we haven't optimized the experience for Elasticsearch v6, and now seems like a good time to do so.

We need to update the mappings for ES v6, which will happen [here](https://github.com/appbaseio/dejavu/blob/dev/live/src/js/helper/esMapping.js) and then use these updated mappings when the ES major version is 6 in this [file](https://github.com/appbaseio/dejavu/blob/dev/live/src/js/table/CreateColumnForm.js). This is a fun issue if someone is interested in taking it up. Otherwise, I will be looking at it shortly.

**Comment by siddharthlatest** [comment]
https://github.com/appbaseio/dejavu/commit/0f49b236f7b940610e0343ba2f57c92a7c0a5e50 fixes this. This will be out in the `1.6.0` release.
