### ISSUE TITLE
Delete the whole Index///

### ISSUE THREAD

**Issue by athempeed** [appbaseio/dejaVu#216]
please do let me know if I can do that from this tool...

#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
I am using as chrome Extension.

#### What is the version of Dejavu that you are using?
1.5.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Hey I am using Dejavu for checking the elastic search data. It is a very good tool to watch and user friendly as well the only problem which I faced is I was not able to find out how to delete the whole index.

**Comment by siddharthlatest** [comment]
@Donjay2101 That's not something we support via Dejavu and believe it's not a great idea to do this from a web browser particularly, since we don't know anything about the underlying cluster (whether backups exist, is it secured, etc).

We offer a managed service appbase.io which has the options to remove an index from the dashboard. Even if you are using an ES cluster elsewhere, this is a relatively trivial operation to perform.
