### ISSUE TITLE
CORS requests from https://opensource.appbase.io

### ISSUE THREAD

**Issue by trautonen** [appbaseio/dejaVu#262]
Running Dejavu `appbaseio/dejavu:3.0.0-alpha.1` from Docker container seems to send requests where origin is `https://opensource.appbase.io`. The query explorer tab does not work at all if that origin is not allowed.

At least `/_settings?human` and `/_mapping/` requests come from that origin. Is this intentional?

**Comment by siddharthlatest** [comment]
@trautonen Yes, we are currently loading the query tab as an iframe which is hosted on `opensource.appbase.io` domain. You would have to allow this origin for using it. Another option you have is to run query explorer as a [separate docker container](https://hub.docker.com/r/appbaseio/mirage).

Since the underlying code is open and written by us, we should be able to build query explorer from source in a future release.

**Comment by piotr-cz** [comment]
I think that CORS instructions could reflect that

```yaml
http.cors.allow-origin: https://dejavu.appbase.io,https://opensource.appbase.io
```
