### ISSUE TITLE
Connecting is a bit unintuitive...

### ISSUE THREAD

**Issue by cawoodm** [appbaseio/dejaVu#270]
When starting dejavu (Chrome Extension) for the first time and it's not clear what we need to do. When we enter the URL `http://myserver:9200` nothing happens. It took several confused minutes to realise that, until an appname is entered, the connect button is disabled. It's obvious once you've done it but one idea might be to leave the button enabled (and put it on the left) and post a warning when it is clicked (or Enter is pressed) about missing connection information.

Alternatively, after the URL is entered/changed you could actually load the list of indices as a dropdown box.

![image](https://user-images.githubusercontent.com/498834/51599376-b396a980-1eff-11e9-8146-281b10426de8.png)

**Comment by elliotxin** [comment]
I got same issue, even I was done the CORS settings.
![image](https://user-images.githubusercontent.com/3390411/51813872-76615b80-22f3-11e9-8578-4ac2c9ea1bb8.png)

**Comment by shentianyi** [comment]
Waiting for an answer. We are under confused too.

**Comment by lakhansamani** [comment]
@cawoodm thanks for the suggestion we will try to incorporate this UX change in upcoming release

**Comment by lakhansamani** [comment]
@elliotxin can you share what exact issue you are facing with above CORS settings?

**Comment by lakhansamani** [comment]
@shentianyi 

In URL input you are supposed to enter elasticsearch cluster URL, example
`http://localhost:9200` and in appname input elasticsearch index name

Any other issues that you are facing?

**Comment by shentianyi** [comment]
I have an elasticsearch run in docker(ip: 172.17.0.3)
I also run dejavu in docker(ip: 172.17.0.4)
I have tried inputing http://172.17.0.3:9200 as URL and "bank" as appname. But the connect button always ran timeout.
I have tried elasticHQ in docker, it works fine. I do not know what is wrong with dejavu.

**Comment by elliotxin** [comment]
@lakhansamani  I put `http://localhost:9200`in URL and index name in appname, then i able to view Data Browser, but when i click the <Import Data> button and used my github ID to login, i got the blank page like this
<img width="1322" alt="screen shot 2019-01-28 at 7 55 56 pm" src="https://user-images.githubusercontent.com/3390411/51834908-beee3880-2336-11e9-9821-950bb11b59b6.png">

If i used my google id to login, i got one error message like this:
<img width="1312" alt="screen shot 2019-01-28 at 7 56 21 pm" src="https://user-images.githubusercontent.com/3390411/51834947-de856100-2336-11e9-8fbc-3866b2378b47.png">

So that's the issue happened for me.

**Comment by lakhansamani** [comment]
@elliotxin that is importer app that you are trying to access, can you try importing data using https://importer.appbase.io/? and let me know if you are facing the same issues

**Comment by lakhansamani** [comment]
@shentianyi can you share the connection error from network request / browser console, it will help us debug more.

**Comment by chrissound** [comment]
Has a UI change actually addressed this issue? I just pulled the latest docker image and ran into this issue.

**Comment by lakhansamani** [comment]
@chrissound can you share the exact problem that you are facing?
