### ISSUE TITLE
Error: Invalid `value` of type `number` supplied to Option, expected `string` when `tags/combobox` is `true`

### ISSUE THREAD

**Issue by oshanz** [appbaseio/dejaVu#333]
Error: Invalid `value` of type `number` supplied to Option, expected `string` when `tags/combobox` is `true`

![Screenshot from 2019-08-29 15-39-07](https://user-images.githubusercontent.com/5364479/63931625-48075280-ca73-11e9-992d-e84935d33079.png)

once I try to click long value field page get blank and get stuck.

**Comment by ShahAnuj2610** [comment]
antd does not support the value of type integer for type `Option` => https://github.com/ant-design/ant-design/issues/2857.
One solution is to `typecast` to the string while mapping the data object, but it will also send the value to the backend as a string. So if it's an array of integers, then instead of `[1, 2]`, it will get sent as `["1", "2"]`. Would there be any side-effects if we do this change? @lakhansamani

**Comment by lakhansamani** [comment]
@oshanz thank you for reporting, issue is fixed here
https://github.com/appbaseio/dejavu/pull/354
