### ISSUE TITLE
Code Refactor and Improvements

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejavu#34]
We have divergent branches that require some major code changes for every release cycle. It would be nice if we can separate code concerns that are specific to a branch (for example, in the chrome app - we have to use an async storage API instead of localstorage; we can move the storage code and it's dependencies in a single file).

We can also create an automated merge script to simplify the release creation process.

**Comment by siddharthlatest** [comment]
https://codeclimate.com/github/appbaseio/dejaVu/issues

**Comment by divyanshu013** [comment]
Adding to the issue, the dejavu codebase is very messy which makes debugging and adding new features very complicated. I propose the following changes to make the codebase simpler and maintainable:
- [x] Do away with globals which makes debugging very tough, this includes the jquery hacks, modals sharing a global logic, the data being shared and modified globally and the feed service being used globally.
- [x] Improve the architecture by avoiding directly injecting the js files into the `index.html` file without proper bundling and transpilation. This has caused a lot of issues related to browser version. It is hard to track and test these issues for all browsers.
- [x] Use a state management (like redux) so that components hold only view logic. This will make the component files smaller (currently the main component files are around 900 lines) and predictable.
- [x] For ajax and async operations we can use thunks. I've also looked into sagas which could probably suit us better, although need time to research on this.
- [x] Use styled components (emotion is great). Although the problem can also be solved with modular styles written using sass or stylus, I think styled components would make the code more reusable in terms of components
- [x] Improve the directory structure. This should go together with the state management point and make debugging or adding new features pleasant.
- [x] Use a windowing approach, for example a virtual list to render only the visible cells. This would need a re-write of the tables logic but improve the performance a lot. Currently a lot of re-renders are needed since all the Cells get updated even if they are not in view.
- [x] Tests. Dejavu can do a lot of things which is great but this makes testing equally difficult. Having tests in place would help us ship better and faster. Plus it reduces the chances of accidentally breaking a feature.

**Comment by siddharthlatest** [comment]
All the changes have been incorporated in the latest release. 🎉
