### ISSUE TITLE
Permissions error when connecting to AWS ElasticSearch

### ISSUE THREAD

**Issue by nikmartin** [appbaseio/dejaVu#79]
Like #61, Using the AWS elastic search service, if I  do a GET of /[indexname]/_mapping in a browser, I get back the index mapping of my elastic search server. Using DejaVu (chrome plugin) , It never appears to connect, and if I look at the developer tools console, I see this: 

`403: Forbidden: http:/[my elastic server]/[index]/_mapping`
`{"message":"'dWF0LmVsYXN0aWMuaGVhbHRoY29zdC5pbzp0ZXN0' not a valid key=value pair (missing equal-sign) in Authorization header: 'Basic dWF0LmVsYXN0aWMuaGVhbHRoY29zdC5pbzp0ZXN0'."}`

Looking at the request headers, the plugin is sending: 
`Authorization: Basic dWF0LmVsYXN0aWMuaGVhbHRoY29zdC5pbzp0ZXN0`

I don't know what that header is for, or why DeJaVu is sending it, but my server needs no authorization headers, it's currently wide open.

I'll be glad to share a URL via message.

**Comment by farhan687** [comment]
Hey @nikmartin ,

Can you share your elastic-search version and chrome extension version? (dejavu is working fine with es v2.4 and 5.x)
Can you just make sure that you follow this step: https://github.com/appbaseio/dejavu#or ?

And please share the URL to farhan687@gmail.com if above steps don't work for you.

**Comment by vanditamathur** [comment]
I have the same problem - When I connect to my AWS ES URL through the browser window, I get the mapping, but not through dejaVu. I get the following error in response -

{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic c2VhcmNoLWtpbmVzaXNwb2MtbDJkNGpxY3dmZ2p0YzZtMzdwdHRrd3hpeXUudXMtZWFzdC0yLmVzLmFtYXpvbmF3cy5jb206dGVzdA=="}

**Comment by siddharthlatest** [comment]
@vanditamathur Since AWS's Elasticsearch service doesn't allow you to configure CORS (which an open-source Elasticsearch cluster lets you do), your best bet it to proxy the request via AWS's API Gateway service. i.e. you provide a API gateway service endpoint to dejavu, and then in the API gateway service, connect a general purpose lambda handler which forwards the request to Elasticsearch.

See #105 for a related issue. Happy to help you in accomplishing this as we want to document a way  for dejavu to work with AWS's ES service. Feel free to file a separate issue of the steps in case you run into a wall. I will be keeping this issue as closed.

**Comment by vanditamathur** [comment]
If it were a CORS issue, why does it work with my browser which is the same domain as dejavu?

**Comment by siddharthlatest** [comment]
When you say it works with your browser, what do you mean? Like you type in the endpoint in the URL bar and it returns a response? A screenshot would help.

**Comment by vanditamathur** [comment]
That's right. When I type in the endpoint to see mappings, I get the result. Screenshot attached
![untitled](https://user-images.githubusercontent.com/27719913/30957727-b71c2cba-a458-11e7-8289-b6dc215eb464.png)

**Comment by vanditamathur** [comment]
Firstly, the error from the online link is different from the one I get if I use the Chrome extension. The message that I put earlier was from the chrome extension. With the onlie link, I get the following error -
"Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://opensource.appbase.io' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

For the online usage of dejavu, the issue seems to be this - 
The response that comes to the pre-flight request has "Access-Control-Allow-Origin" header set to *
However, it seems that if you are making the request using the "withCredentials" flag set to true, then a wildcard response is not acceptable. 
Since AWS ES seems to be sending the wildcard in response, this would mean that you should not make the request with the "withCredentials" flag set to true. It should be set to false.

**Comment by siddharthlatest** [comment]
Related to the screenshot: Thanks for confirming. CORS restrictions don't apply when you type a URL in the browser, they only apply to programmatic requests made by an app's JS that runs within the browser runtime. So what you're observing is inline with a CORS issue.

---

On the `withCredentials`, you bring up an interesting point. Can you file that as a **new issue**? We will test on our end and see if indeed not passing `withCredentials` will let the requests pass by.
